name: Build And Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true

jobs:
  release:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15.1
    - name: Install Homebrew kegs
      run: make setup-brew
    - name: Build for iOS
      run: make build-for-testing-ios
  
    - name: Create and push tag
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git tag -a $TAG -m "Release $TAG"
        git push origin $TAG
      env:
        TAG: ${{ github.event.inputs.versionName }}

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: mikepenz/action-gh-release@v0.2.0-a03
      with:
        body: ${{steps.github_release.outputs.changelog}}
        tag_name: ${{ github.event.inputs.versionName }}
